num_overdue_loans:
  - value: 0
    score: 30
  - max: 1
    score: 10
  - max: 100
    score: 0
    remark: "Есть просроченные кредиты"

overdue_ratio:
  - max: 0.03
    score: 30
  - max: 0.1
    score: 15
  - max: 0.5
    score: 5
  - max: 1.0
    score: 0
    remark: "Высокая доля просрочки"

max_credit_term:
  - max: 12
    score: 20
  - max: 24
    score: 10
  - max: 60
    score: 5
  - max: 999
    score: 0
    remark: "Слишком длинный срок кредитования"

months_since_first_credit:
  - min: 60
    score: 20
  - min: 36
    score: 10
  - min: 12
    score: 5
  - min: 0
    score: 0
    remark: "Мало опыта в кредитовании"

missed_payment_streak:
  - max: 0
    score: 30
  - max: 2
    score: 10
  - max: 100
    score: 0
    remark: "Серии пропущенных платежей"

salary_gap_months:
  - max: 1
    score: 20
  - max: 3
    score: 10
  - max: 6
    score: 5
  - max: 100
    score: 0
    remark: "Долгие периоды без дохода"

has_credit_cards:
  - value: True
    score: 15
  - value: False
    score: 5

payment_to_limit_ratio:
  - max: 0.2
    score: 20
  - max: 0.5
    score: 10
  - max: 1.0
    score: 0
    remark: "Высокая нагрузка по лимитам"

avg_actual_repayment:
  - min: 3000000
    score: 20
  - min: 1500000
    score: 10
  - min: 0
    score: 0
    remark: "Низкий средний платёж"

salary_last_6mo_avg:
  - min: 20000000
    score: 80
  - min: 10000000
    score: 60
  - min: 5000000
    score: 40
  - min: 2000000
    score: 20
  - min: 0
    score: 0
    remark: "Стоп фактор: низкий доход"

employment_tenure_days:
  - min: 1460
    score: 40
  - min: 730
    score: 30
  - min: 365
    score: 20
  - min: 0
    score: 0
    remark: "Меньше 1 года стажа"

salary_growth:
  - min: 1.1
    score: 30
  - min: 1.0
    score: 20
  - min: 0.9
    score: 10
  - min: -9999
    score: 0
    remark: "Падение дохода"

dti_ratio:
  - max: 0.3
    score: 30
  - max: 0.5
    score: 20
  - max: 0.7
    score: 10
  - max: 1.0
    score: 0
    remark: "DTI выше 70%"

pti_ratio:
  - max: 0.2
    score: 30
  - max: 0.4
    score: 15
  - max: 0.6
    score: 5
  - max: 1.0
    score: 0
    remark: "PTI выше 60%"

credit_utilization_ratio:
  - max: 0.2
    score: 20
  - max: 0.5
    score: 10
  - max: 0.7
    score: 5
  - max: 1.0
    score: 0
    remark: "Высокая кредитная нагрузка"

num_contingent_liabilities:
  - value: 0
    score: 20
  - max: 2
    score: 10
  - max: 100
    score: 0
    remark: "Много обязательств"

recent_overdue_count:
  - value: 0
    score: 30
  - max: 2
    score: 10
  - max: 100
    score: 0
    remark: "Последние просрочки"

katm_score:
  - min: 400
    score: 30
  - min: 250
    score: 20
  - min: 150
    score: 10
  - min: 0
    score: 0
    remark: "Стоп фактор: низкий балл KATM"

katm_score_class:
  - value: "A1"
    score: 20
  - value: "B1"
    score: 10
  - value: "C2"
    score: 0
    remark: "Стоп фактор: класс C2 по KATM"

safe_payment_capability:
  - min: 10000000
    score: 30
  - min: 5000000
    score: 20
  - min: 2000000
    score: 10
  - min: 0
    score: 0
    remark: "Недостаточная платёжеспособность"

